import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../common/components/GoogleAdSense/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aptitude tester",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: { apple: "/media/img/arrow.png" },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#317EFB" />
        <Header pId="7589879263289412" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
