import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Aptitude tester",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: { apple: '/media/img/arrow.png' },
  themeColor: '#f69435'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#317EFB" /></head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
